### PR TITLE
Implement User-Specific Review Retrieval Functionality

### LINKED ISSUE #8: Backend 3: Controller methods to get all reviews for a given user (the user that is logged in) ~  User-specific Review Retrieval
Objective: Enable users to retrieve their own reviews.

Tasks:
Develop a GET endpoint to fetch all reviews by a specific user (/api/reviews?userId=x).

Full mutation and line coverage testing must be implemented.

### PR DESCRIPTION
**Pull request by jayster7101**
MERGE AFTER #52 

**Description:**
This pull request adds an API endpoint that allows users to retrieve reviews they have submitted. This ensures that users can access only their own reviews, maintaining privacy and security.

**Key Changes:**
- Test Method: Added a_logged_in_user_can_get_own_reviews_list() to verify that the endpoint correctly returns a user's reviews.
- API Endpoint: Implemented GET /api/reviews/userReviews, accessible only to authenticated users with 'ROLE_USER'.
- Repository Method: Included a method in ReviewRepository to fetch reviews by the student ID derived from the authenticated user.

**Testing:**
- Tests cover scenarios including retrieving single and multiple reviews ensuring both security and functionality are maintained.
- Jacoco is at 100 %
- mutation testing at 100 %

[Dokku instance](https://proj-dining-dev-jayster7101.dokku-16.cs.ucsb.edu/) *Read below first*
To test on dokku: 
1) must first ensure data is populated in menuItems db:
- navigate to the swagger endpoint: https://proj-dining-dev-jayster7101.dokku-16.cs.ucsb.edu/swagger-ui/index.html#/UCSBDiningMenuItems/get_menu_items
- Then enter in values ex: date/time = 2024-11-12T08:08:08 | dining-commons-code = portola | meal-code = dinner

2) Make a review : https://proj-dining-dev-jayster7101.dokku-16.cs.ucsb.edu/swagger-ui/index.html#/Review/postReview

3) Request reviews made by you only: https://proj-dining-dev-jayster7101.dokku-16.cs.ucsb.edu/swagger-ui/index.html#/Review/get_all_review_by_user_id

closes #8

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
This PR builds on an earlier one that has considerable Code Review feedback requesting changes; those changes should be fully integrated into this PR before it is ready for review.  So I'm changing it to a draft PR for now.

**Review by Salshriaan — DISMISSED** [review]
LGTM

**Review by Salshriaan — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM... will test on dokku

**Pull request merged**
